{"nbformat":4,"nbformat_minor":0,"metadata":{"anaconda-cloud":{},"kernelspec":{"display_name":"Python [conda root]","language":"python","name":"conda-root-py"},"language_info":{"codemirror_mode":{"name":"ipython","version":2},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython2","version":"2.7.12"},"colab":{"name":"5_Handling_Errors.ipynb","provenance":[],"collapsed_sections":[]}},"cells":[{"cell_type":"markdown","metadata":{"id":"HhNyM6YQEPTZ","colab_type":"text"},"source":["# Synopsis\n","\n","In this unit we will learn that:\n","\n","1. **Programming errors** are inevitable as you develop code.\n","\n","    1. Syntax errors are easy to find (the code does not run or crashes) \n","    \n","    2. Type, Name, Index, Value, and Attribute errors are easy to find (the code crashes)\n","    \n","    3. Logical errors can be extremely hard to identify (the code may run and the results may appear plausible)\n","    \n","2. **Errors messages** can be extremely helpful in finding and correcting syntax errors and calculation or variable type errors.\n","\n","3. **Error handling** commands enable code to exit graciously when an exceptions occur.\n","\n","4. **Unit testing** is essential in order to avoid logical errors. \n","\n","\n","\n","\n"]},{"cell_type":"markdown","metadata":{"id":"i9WFrgP5EPTc","colab_type":"text"},"source":["# Programming and Errors\n","\n","As as programs grow in complexity and the number of lines of code and instructions for the computer to carry out grow, the more likely it is that our code will have errors. Already you've seen some errors as we've learned what can and can't be done, but now it's time look at errors in a more systematic manner. \n","\n","Just like there are different data types, there are also different error types. Having different error types helps us to more easily identify what has gone wrong in our code. \n","\n","## Syntax errors\n","\n","Like all programming languages, Python needs you to write code in a **syntaxically correct manner** so that it can understand your commands and translate them to the machine. If you don't follow the correct syntax in your code, such as not having matched parentheses, brackets, or quotations marks, your code will generate a `SyntaxError`."]},{"cell_type":"code","metadata":{"id":"cIN69ZbEEPTd","colab_type":"code","colab":{"base_uri":"https://localhost:8080/","height":131},"executionInfo":{"status":"error","timestamp":1590826012958,"user_tz":-480,"elapsed":940,"user":{"displayName":"Desmond Sek","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GjQj9ANFvLsRLkJAoNiRe9I6br32aYvAs1rqTwiF6M=s64","userId":"15004601375355093954"}},"outputId":"356b0feb-c84c-4976-960e-3de8f5e43597"},"source":["value = 3\n","sentence = 'I am a sentence\n","print(value)"],"execution_count":null,"outputs":[{"output_type":"error","ename":"SyntaxError","evalue":"ignored","traceback":["\u001b[0;36m  File \u001b[0;32m\"<ipython-input-1-5cb474b59c7b>\"\u001b[0;36m, line \u001b[0;32m2\u001b[0m\n\u001b[0;31m    sentence = 'I am a sentence\u001b[0m\n\u001b[0m                               ^\u001b[0m\n\u001b[0;31mSyntaxError\u001b[0m\u001b[0;31m:\u001b[0m EOL while scanning string literal\n"]}]},{"cell_type":"markdown","metadata":{"id":"RNyXZZoyEPTi","colab_type":"text"},"source":["What you're seeing above is the **exception** and the **traceback**. The first part is the **traceback**.\n","\n","`File \"<ipython-input-2-a6097ed4dc2e>\"`\n","\n","It tells us the \"file\" that the compiler was processing when the error occurred. Since we are using an Jupyter notebook and are not calling any functions defined in external files, this line is not providing any additional information to us.\n","\n","We then learn that the error occurred at \n","\n","`line 2`\n","\n","and that the parsing problem occurred at \n","\n","`sentence = 'I am a sentence`\n","\n","**Be aware that this information isn't always accurate**. Depending upon the type of error and the complexity of the line of code, the actual error could be above or below where it points out that the error is occurring.\n","\n","The second part is the **exception**. \n","\n","`SyntaxError: EOL while scanning string literal`\n","\n","It tells us what issue generated the error. In this case, we have a `SyntaxError` because Python reached the end of the line (`EOL`) while it was scanning the string we started with `'` and it couldn't find the closing `'`.\n","\n","Another type of syntax error that can occur in Python is an `Indentation Error`.   Consider the following code snippet:"]},{"cell_type":"code","metadata":{"id":"c9GCH8C1EPTj","colab_type":"code","colab":{"base_uri":"https://localhost:8080/","height":131},"executionInfo":{"status":"error","timestamp":1590826123306,"user_tz":-480,"elapsed":1814,"user":{"displayName":"Desmond Sek","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GjQj9ANFvLsRLkJAoNiRe9I6br32aYvAs1rqTwiF6M=s64","userId":"15004601375355093954"}},"outputId":"ff474428-6eeb-4363-e75a-56a5d93e5955"},"source":["for i in range(3):\n","  j = i * 2\n","    print(i, j)\n"],"execution_count":null,"outputs":[{"output_type":"error","ename":"IndentationError","evalue":"ignored","traceback":["\u001b[0;36m  File \u001b[0;32m\"<ipython-input-2-42e4af0966bb>\"\u001b[0;36m, line \u001b[0;32m3\u001b[0m\n\u001b[0;31m    print(i, j)\u001b[0m\n\u001b[0m    ^\u001b[0m\n\u001b[0;31mIndentationError\u001b[0m\u001b[0;31m:\u001b[0m unexpected indent\n"]}]},{"cell_type":"markdown","metadata":{"id":"kdzad5qrEPTn","colab_type":"text"},"source":["The third line in the code snippet - `print(i, j)` - should be aligned vertically with the beginning of the second line - `j = i * 2` - but it is not. "]},{"cell_type":"markdown","metadata":{"id":"0AVkxXbjEPTp","colab_type":"text"},"source":["## Type errors\n","\n","A very common Python error is the `TypeError`. This happens when we try to use a method that is for one data type on another data type that does not support it. Remember how strings cannot be subtracted or divided? "]},{"cell_type":"code","metadata":{"id":"jfMZcnRVEPTq","colab_type":"code","colab":{"base_uri":"https://localhost:8080/","height":235},"executionInfo":{"status":"error","timestamp":1590826228818,"user_tz":-480,"elapsed":1028,"user":{"displayName":"Desmond Sek","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GjQj9ANFvLsRLkJAoNiRe9I6br32aYvAs1rqTwiF6M=s64","userId":"15004601375355093954"}},"outputId":"9fdaa789-1baa-489e-a4a9-4dcc396a4a7a"},"source":["new_string = 'cat' + 'dog'\n","print(new_string)\n","new_string = 'cat' - 'dog'\n","print(new_string)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["catdog\n"],"name":"stdout"},{"output_type":"error","ename":"TypeError","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)","\u001b[0;32m<ipython-input-3-a8e45a5d14a7>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0mnew_string\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m'cat'\u001b[0m \u001b[0;34m+\u001b[0m \u001b[0;34m'dog'\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      2\u001b[0m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mnew_string\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 3\u001b[0;31m \u001b[0mnew_string\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m'cat'\u001b[0m \u001b[0;34m-\u001b[0m \u001b[0;34m'dog'\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      4\u001b[0m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mnew_string\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mTypeError\u001b[0m: unsupported operand type(s) for -: 'str' and 'str'"]}]},{"cell_type":"markdown","metadata":{"id":"zqrWvxFoEPTt","colab_type":"text"},"source":["As you can see, the Python interpreter correctly executed the first two lines of our code and printed\n","\n","`catdog`\n","\n","Also, as expected, Python tells the line the error occurred on. Python does not have a rule for how to subtract strings, so it lets us know that the operation `-` is not supported and informs us that this is a `TypeError`."]},{"cell_type":"code","metadata":{"id":"nYEh_gXNEPTu","colab_type":"code","colab":{"base_uri":"https://localhost:8080/","height":252},"executionInfo":{"status":"error","timestamp":1590826283986,"user_tz":-480,"elapsed":931,"user":{"displayName":"Desmond Sek","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GjQj9ANFvLsRLkJAoNiRe9I6br32aYvAs1rqTwiF6M=s64","userId":"15004601375355093954"}},"outputId":"218b23ca-b9c5-4d88-ba74-c6b0ec86a119"},"source":["new_string = 'cat' * 3\n","print(new_string)\n","\n","new_string = 'cat' + 'dog'\n","print(new_string)\n","\n","new_string = 'cat' / 3\n","print(new_string)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["catcatcat\n","catdog\n"],"name":"stdout"},{"output_type":"error","ename":"TypeError","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)","\u001b[0;32m<ipython-input-4-9d9d76a8d67a>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mnew_string\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      6\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 7\u001b[0;31m \u001b[0mnew_string\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m'cat'\u001b[0m \u001b[0;34m/\u001b[0m \u001b[0;36m3\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      8\u001b[0m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mnew_string\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mTypeError\u001b[0m: unsupported operand type(s) for /: 'str' and 'int'"]}]},{"cell_type":"markdown","metadata":{"id":"s5biRIZLEPTx","colab_type":"text"},"source":["We see that here is a `TypeError` in line 4.  Why don't you correct it and see what happens next?\n","\n","**Remember:** The type of data you're working with really matters, and that's what `TypeError`'s are all about. A valid operation for a `list` might not work for a `tuple` and Python will try to remind you of that fact.\n","\n","## Name errors\n","\n","Variables in Python must be initialized before they can be used.  If we try to use a variable prior to initialization, we will get a `NameError`. For example, imagine we try to use the new variable `party`"]},{"cell_type":"code","metadata":{"id":"TPQ7Y2XdEPTy","colab_type":"code","colab":{"base_uri":"https://localhost:8080/","height":183},"executionInfo":{"status":"error","timestamp":1590826307472,"user_tz":-480,"elapsed":1416,"user":{"displayName":"Desmond Sek","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GjQj9ANFvLsRLkJAoNiRe9I6br32aYvAs1rqTwiF6M=s64","userId":"15004601375355093954"}},"outputId":"5d54c000-0afa-437b-921e-01d8064ecf0a"},"source":["party = 5\n","print( party2 )"],"execution_count":null,"outputs":[{"output_type":"error","ename":"NameError","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)","\u001b[0;32m<ipython-input-5-334f4e9f64a4>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0mparty\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;36m5\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 2\u001b[0;31m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m \u001b[0mparty2\u001b[0m \u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;31mNameError\u001b[0m: name 'party2' is not defined"]}]},{"cell_type":"markdown","metadata":{"id":"qmh-xpsxEPT1","colab_type":"text"},"source":["## Index errors\n","\n","\n","As you will remember, specific characters in a string can be accessed using an `index`. The index ranges from 0 to the length of the string minus one.  If we try to access a character in a string by index, and that index doesn't exist in the variable, the Python interpreter returns an `IndexError`."]},{"cell_type":"code","metadata":{"id":"Xqli--jpEPT2","colab_type":"code","colab":{"base_uri":"https://localhost:8080/","height":217},"executionInfo":{"status":"error","timestamp":1590826333049,"user_tz":-480,"elapsed":922,"user":{"displayName":"Desmond Sek","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GjQj9ANFvLsRLkJAoNiRe9I6br32aYvAs1rqTwiF6M=s64","userId":"15004601375355093954"}},"outputId":"82968a6f-31f7-4b15-ad98-f962d9898eeb"},"source":["example_string = 'abcdefg'\n","print( example_string[2] ) \n","print( example_string[12] ) "],"execution_count":null,"outputs":[{"output_type":"stream","text":["c\n"],"name":"stdout"},{"output_type":"error","ename":"IndexError","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mIndexError\u001b[0m                                Traceback (most recent call last)","\u001b[0;32m<ipython-input-6-93a9f595a614>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0mexample_string\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m'abcdefg'\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      2\u001b[0m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m \u001b[0mexample_string\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m2\u001b[0m\u001b[0;34m]\u001b[0m \u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 3\u001b[0;31m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m \u001b[0mexample_string\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m12\u001b[0m\u001b[0;34m]\u001b[0m \u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;31mIndexError\u001b[0m: string index out of range"]}]},{"cell_type":"markdown","metadata":{"id":"9HItuXOjEPT5","colab_type":"text"},"source":["A similar type of error is a `KeyError` which can occur when dealing with a very powerful data type we will describe later;   dictionaries. \n","\n","## Value errors\n","\n","Functions (or methods) in Python are written to only work with arguments of specific types. If we call a function with a non-compliant argument, we get a `ValueError`. "]},{"cell_type":"code","metadata":{"id":"OG69rxhvEPT7","colab_type":"code","colab":{"base_uri":"https://localhost:8080/","height":252},"executionInfo":{"status":"error","timestamp":1590826358994,"user_tz":-480,"elapsed":994,"user":{"displayName":"Desmond Sek","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GjQj9ANFvLsRLkJAoNiRe9I6br32aYvAs1rqTwiF6M=s64","userId":"15004601375355093954"}},"outputId":"57cb147b-2287-40d6-cdb3-68219f283f73"},"source":["example_string = 'abcd'\n","\n","print( example_string )\n","print( type(example_string) ) # fata type\n","print( len(example_string) ) # for the length\n","float(example_string)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["abcd\n","<class 'str'>\n","4\n"],"name":"stdout"},{"output_type":"error","ename":"ValueError","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)","\u001b[0;32m<ipython-input-7-15b3b21b3d38>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m \u001b[0mtype\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mexample_string\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;34m)\u001b[0m \u001b[0;31m# fata type\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m \u001b[0mlen\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mexample_string\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;34m)\u001b[0m \u001b[0;31m# for the length\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 6\u001b[0;31m \u001b[0mfloat\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mexample_string\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;31mValueError\u001b[0m: could not convert string to float: 'abcd'"]}]},{"cell_type":"markdown","metadata":{"id":"awnyvrIU2-T6","colab_type":"text"},"source":[""]},{"cell_type":"markdown","metadata":{"id":"XVph-oWhEPT-","colab_type":"text"},"source":["## Attribute errors\n","\n","Many Python objects have attributes that can be easily retrieved using the name of the attribute. For example, an attribute of a string is its capitalized form or its upper case form. However, while one can obtain the length of a string using the default function `len()`, strings do not have a `len()` attribute."]},{"cell_type":"code","metadata":{"id":"-CaAKNfsEPT_","colab_type":"code","colab":{"base_uri":"https://localhost:8080/","height":269},"executionInfo":{"status":"error","timestamp":1590826411638,"user_tz":-480,"elapsed":1163,"user":{"displayName":"Desmond Sek","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GjQj9ANFvLsRLkJAoNiRe9I6br32aYvAs1rqTwiF6M=s64","userId":"15004601375355093954"}},"outputId":"f3b7287d-f018-4ec0-a0f4-c8f5381f9ab3"},"source":["print( example_string.capitalize() )\n","print( example_string.upper() )\n","print( example_string.lower() )\n","print( len(example_string) )\n","print( example_string.len() )"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Abcd\n","ABCD\n","abcd\n","4\n"],"name":"stdout"},{"output_type":"error","ename":"AttributeError","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)","\u001b[0;32m<ipython-input-8-c8e210990240>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m \u001b[0mexample_string\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mlower\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m \u001b[0mlen\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mexample_string\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 5\u001b[0;31m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m \u001b[0mexample_string\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mlen\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;31mAttributeError\u001b[0m: 'str' object has no attribute 'len'"]}]},{"cell_type":"markdown","metadata":{"id":"TFeEn_cIEPUB","colab_type":"text"},"source":["The examples above illustrate some of the errors that you are most likely to encounter when programming. For the full list of exceptions and errors you can refer to the official Python documentation.\n","\n","Python Built-in Exceptions docs:\n","https://docs.python.org/3.4/library/exceptions.html\n","\n","Python Error Handling docs:\n","https://docs.python.org/3.4/tutorial/errors.html\n","\n","The important thing to remember is to look at the error message. It takes a little bit of practice but pretty soon you'll be able to see that the Python interpreter is trying its hardest to tell you exactly where and why you made a mistake."]},{"cell_type":"markdown","metadata":{"id":"nlhpLAvuEPUC","colab_type":"text"},"source":["+++"]},{"cell_type":"markdown","metadata":{"id":"GgVKi_8iEPUD","colab_type":"text"},"source":["## Handling exceptions\n","\n","Code with syntax errors will not run. However, code with other types of errors will still run until it comes upon an exception, at which point it will crash.  This is not nice. As much as possible, you will want to prevent your code from crashing so that you can save whatever information has been generated up to that point and also that you can tell the user of the program WHY the code crashed.\n","\n","Consider the following situation: We want to use the `input()` function to ask for a number and then return the square of that number."]},{"cell_type":"code","metadata":{"id":"WLhAqGZxEPUE","colab_type":"code","colab":{"base_uri":"https://localhost:8080/","height":289},"executionInfo":{"status":"error","timestamp":1590826569226,"user_tz":-480,"elapsed":5171,"user":{"displayName":"Desmond Sek","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GjQj9ANFvLsRLkJAoNiRe9I6br32aYvAs1rqTwiF6M=s64","userId":"15004601375355093954"}},"outputId":"0f6fd0fc-c00e-4475-8eb2-e5a55cdea64e"},"source":["number_to_square = input(\"What number do you want to know the square of? \")\n","print( type(number_to_square) )\n","\n","# Note that number_to_square is a string, in order to perform calculations with it, we have to transform it to an integer\n","number = int(number_to_square)\n","\n","print(\"Your number squared is \", number**2)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["What number do you want to know the square of? a\n","<class 'str'>\n"],"name":"stdout"},{"output_type":"error","ename":"ValueError","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)","\u001b[0;32m<ipython-input-10-f67056cbf1f2>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0;31m# Note that number_to_square is a string, in order to perform calculations with it, we have to transform it to an integer\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 5\u001b[0;31m \u001b[0mnumber\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mnumber_to_square\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      6\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      7\u001b[0m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Your number squared is \"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mnumber\u001b[0m\u001b[0;34m**\u001b[0m\u001b[0;36m2\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mValueError\u001b[0m: invalid literal for int() with base 10: 'a'"]}]},{"cell_type":"markdown","metadata":{"id":"w4F2HbHlEPUG","colab_type":"text"},"source":["But what would happen if you entered 'a' instead of 3? Try it!\n","\n",".\n","\n",".\n","\n",".\n","\n",".\n","\n",".\n","\n",".\n","\n",".\n","\n",".\n","\n",".\n","\n",".\n","\n",".\n","\n",".\n","\n",".\n","\n",".\n","\n",".\n","\n",".\n","\n",".\n","\n",".\n","\n",".\n","\n","\n","You got a `ValueError` because you can't convert 'a' to an integer. \n","\n","In order to avoid having the program crash, we can use the `try ... except ...` construction so that we test for possible errors and avoid the crash."]},{"cell_type":"code","metadata":{"id":"-79BfFgoEPUH","colab_type":"code","colab":{"base_uri":"https://localhost:8080/","height":69},"executionInfo":{"status":"ok","timestamp":1590826824043,"user_tz":-480,"elapsed":6644,"user":{"displayName":"Desmond Sek","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GjQj9ANFvLsRLkJAoNiRe9I6br32aYvAs1rqTwiF6M=s64","userId":"15004601375355093954"}},"outputId":"5ba11c6f-d239-4cd7-f479-51ed733751b5"},"source":["number_to_square = input(\"What number do you want to know the square of? \")\n","print( type(number_to_square) )\n","\n","# Note that number_to_square is a string, in order to perform calculations with it, we have to transform it to an integer\n","try: \n","    number = int(number_to_square)\n","    print(\"Your number squared is \", number**2)\n","except ValueError:\n","    print(\"You didn't enter an integer!\")"],"execution_count":null,"outputs":[{"output_type":"stream","text":["What number do you want to know the square of? a\n","<class 'str'>\n","You didn't enter an integer!\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"tw5xrtdTmW4-","colab_type":"code","colab":{"base_uri":"https://localhost:8080/","height":35},"executionInfo":{"status":"ok","timestamp":1590826933399,"user_tz":-480,"elapsed":890,"user":{"displayName":"Desmond Sek","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GjQj9ANFvLsRLkJAoNiRe9I6br32aYvAs1rqTwiF6M=s64","userId":"15004601375355093954"}},"outputId":"58a6ce9f-364f-4edc-cbf5-6cde9ff712b9"},"source":["var1 = 5\n","try:\n","  print(var1)\n","except NameError:\n","  print('I think you ate too much food!!')"],"execution_count":null,"outputs":[{"output_type":"stream","text":["5\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"j1mfZ7NvmiVg","colab_type":"code","colab":{"base_uri":"https://localhost:8080/","height":35},"executionInfo":{"status":"ok","timestamp":1590826936906,"user_tz":-480,"elapsed":950,"user":{"displayName":"Desmond Sek","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GjQj9ANFvLsRLkJAoNiRe9I6br32aYvAs1rqTwiF6M=s64","userId":"15004601375355093954"}},"outputId":"6c317e6c-c520-48b8-de22-0aedee21e1b1"},"source":["var1 = 5\n","try:\n","  print(var2)\n","except NameError:\n","  print('I think you entered the wrong variable name in the code above')"],"execution_count":null,"outputs":[{"output_type":"stream","text":["I think you entered the wrong variable name in the code above\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"rIaphlGtEPUJ","colab_type":"text"},"source":["When you are writing code that takes as inputs information provided by a user or from a source over which you have no control, **it is crucial that you test your code for all possible types of inputs**. That way you will prevent the user from having the pleasure of making your code crash.\n","\n","However, if the functions in your code are taking as input only information that is generated internally by your code, you will not need to make those checks.  **This does not mean that your code will not generate exceptions**. Your code might very well generate exceptions because of logical errors in your code: **That is your code might not be doing what you expect it to be doing!**\n","\n"]},{"cell_type":"markdown","metadata":{"id":"i6VMUEKGEPUL","colab_type":"text"},"source":["# Checking the validity of your code\n","\n","In order to make sure that your code has no logical errors, you must check its validity. That is, you must check that it returns the right answer for cases in which you know what the right answer is. **You will need to test the correctness of the output of your code for a diverse set of possibilities in order to have confidence in its validity**.\n","\n","This is where **unit testing** comes in.  Unit test are a set of "]},{"cell_type":"code","metadata":{"id":"XmX6VTQnEPUM","colab_type":"code","colab":{}},"source":["def square( number ):\n","    \"\"\"\n","    This functions asks the user for an integer and returns its square\n","    \n","    Parameters:\n","    -----------\n","        number : (int)\n","        \n","    Output:\n","    -------\n","        square_of_number: (int)\n","    \"\"\"\n","    square_of_number = number**2\n","    return square_of_number"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"0vPSX2iyEPUO","colab_type":"code","colab":{"base_uri":"https://localhost:8080/","height":52},"executionInfo":{"status":"ok","timestamp":1590827061125,"user_tz":-480,"elapsed":6070,"user":{"displayName":"Desmond Sek","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GjQj9ANFvLsRLkJAoNiRe9I6br32aYvAs1rqTwiF6M=s64","userId":"15004601375355093954"}},"outputId":"4999bc44-94ed-4447-a9ec-6c640998b855"},"source":["number_string = input('Please, enter the integer you would like to have squared:')\n","try:\n","    number = int(number_string)\n","    print('The square of {0} is {1}.'.format(number, square(number)) )\n","except:\n","    print('You did not provide an integer!')\n"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Please, enter the integer you would like to have squared:2\n","The square of 2 is 4.\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"JgOvqW4oEPUR","colab_type":"text"},"source":["Testing like this is good. But it is unsystematic and hard to replicate in case we make changes to our code.  **The systematic way to test code is using assertions**. \n","\n","Those can be kept with our code and easily run in case we make changes to the code."]},{"cell_type":"code","metadata":{"id":"4Qkh2AmGEPUW","colab_type":"code","colab":{"base_uri":"https://localhost:8080/","height":200},"executionInfo":{"status":"error","timestamp":1590827118003,"user_tz":-480,"elapsed":1381,"user":{"displayName":"Desmond Sek","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GjQj9ANFvLsRLkJAoNiRe9I6br32aYvAs1rqTwiF6M=s64","userId":"15004601375355093954"}},"outputId":"ef485496-4015-44ab-efc1-2c06668de32a"},"source":["assert(square(3) == 8)\n","assert(square(5) == 25)\n","assert(square(2) == 4)"],"execution_count":null,"outputs":[{"output_type":"error","ename":"AssertionError","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mAssertionError\u001b[0m                            Traceback (most recent call last)","\u001b[0;32m<ipython-input-18-786f87eaec9a>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0;32massert\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0msquare\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m3\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0;36m8\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      2\u001b[0m \u001b[0;32massert\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0msquare\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m5\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0;36m25\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0;32massert\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0msquare\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m2\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0;36m4\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mAssertionError\u001b[0m: "]}]},{"cell_type":"code","metadata":{"id":"NnC2idgES_eD","colab_type":"code","colab":{"base_uri":"https://localhost:8080/","height":131},"executionInfo":{"status":"error","timestamp":1590827101164,"user_tz":-480,"elapsed":1233,"user":{"displayName":"Desmond Sek","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GjQj9ANFvLsRLkJAoNiRe9I6br32aYvAs1rqTwiF6M=s64","userId":"15004601375355093954"}},"outputId":"50019264-0030-4bbf-954c-84a27a1ce5d1"},"source":[""],"execution_count":null,"outputs":[{"output_type":"error","ename":"SyntaxError","evalue":"ignored","traceback":["\u001b[0;36m  File \u001b[0;32m\"<ipython-input-17-f99b15b86d7c>\"\u001b[0;36m, line \u001b[0;32m1\u001b[0m\n\u001b[0;31m    print(assert(square(3) == 9))\u001b[0m\n\u001b[0m               ^\u001b[0m\n\u001b[0;31mSyntaxError\u001b[0m\u001b[0;31m:\u001b[0m invalid syntax\n"]}]},{"cell_type":"code","metadata":{"id":"7daHOXpIryZc","colab_type":"code","colab":{}},"source":[""],"execution_count":null,"outputs":[]}]}